### PR TITLE
add spectral window shift

### PR DESCRIPTION
**Pull request by nicholebarry**
Addresses #97

This needs to be checked in the math by someone who understands it better.

### CODE REVIEW

**Comment by bhazelton** [comment]
This doesn't make sense to me. The concept of the center bin in k-space doesn't apply in frequency space, where this window is constructed and used.

**Comment by nicholebarry** [comment]
I'm a little confused as to how we deal with an asymmetric window function (i.e. even number of frequency channels) if the proposed shifting isn't right.

Would it be right to have a symmetric window function that doesn't peak at 1 and has two maximums about the center in the even number case?

**Comment by bhazelton** [comment]
We can either use a symmetric or an asymmetric window in the case of an even number of frequency channels. Currently, it's hard coded to an asymmetric window (the keyword `periodic` is set), but either is ok. I'm open to making that option accessible from the wrapper if you like.

Wikipedia has a nice section on this: https://en.wikipedia.org/wiki/Window_function#Symmetry

**Comment by bhazelton** [comment]
I'd like to close this in favor of the approach I suggest in #124

**Comment by bhazelton** [comment]
after talking to @nicholebarry, we're closing in favor of #127

**Pull request closed without merging**
