### PR TITLE
make 2d power spectra with voxel mask from 1d power spectra

### PR DESCRIPTION
**Pull request by bhazelton**
addressing issue #15.

@nicholebarry can you test that this works as expected?

### CODE REVIEW

**Comment by nicholebarry** [comment]
Do I need to set any specific keywords?

**Comment by bhazelton** [comment]
Yes, sorry, the plotting keyword to set is plot_2d_masked. You should get the standard ps type plots for each of the 1d masking situations (typically no wedge, fov wedge, horizon wedge), including all the masking that is done for the 1d power spectra.

**Comment by nicholebarry** [comment]
Resulting images look correct. I haven't been able to locate all of the PS files to check saved quantities though, in part because there are many. 

It would be helpful to start a documentation page (keywords and outputs) that we can fill in as we go. It will also help me a bunch in terms of testing.

**Comment by bhazelton** [comment]
Yes. For now, the new 2d save files have similar names as before, but they have the 1d limit info in them and they end in *_2dkpower_1dmask.idlsave

**Pull request merged**
