### PR TITLE
updated hyperfine freq and c

### PR DESCRIPTION
**Pull request by nicholebarry**
Updated values to be more precise. Addresses #99 and #102

### CODE REVIEW

**Comment by bhazelton** [comment]
Looks totally reasonable/

Do you have a difference 2D PS plot for this? It'd be nice to document what effect it has.

**Comment by nicholebarry** [comment]
master minus updated numbers. There's a small "improvement," but really its just a small normalization change I believe.
ps__master_compare_minus_updatenum

**Comment by miguelfmorales** [comment]
Do you have the ratio plot?

**Comment by nicholebarry** [comment]
And here is the ratio. There are very small changes. I changed the speed of light from a float to a double, so that might make sense.
ps__master_compare_minus_updatenum_ratio

**Pull request merged**
