### PR TITLE
Added support for passing in 3D mask or bin arrays to 1D binning code

### PR DESCRIPTION
**Pull request by bhazelton**

### CODE REVIEW

**Comment by bhazelton** [comment]
This is a significant re-write of the 1d binning code to support passing in either a 3d mask (1s and 0s) to dictate which voxels to include or a 3d bin array that tells the code which 1d bin to put each voxel into.

Details:
Either the mask array or the bin array is passed in using the bin_arr_3d keyword (it is treated as a mask if there are no values greater than 1, any voxels with zero are excluded from the binning)
If nothing is specified, the masking and binning is worked out as before from the other keywords (e.g. kperp_range, wedge_amp, kperp_power, etc) and a 3d bin array is generated as before and passed out via the bin_arr_3d keyword -- it can be passed back in to reproduce the same binning. If a mask array is passed in (no values greater than 1 in bin_arr_3d) then the only additional masking that is applied is the binning required for the density correction (if that is requested) and the binning is worked out as before from other keywords (e.g. kperp_power) and a 3d bin array is generated as before and passed out via the bin_arr_3d keyword -- it can be passed back in to reproduce the same binning.

Note that this allows any crazy masking or binning you want, including @miguelfmorales' 'diagonal binning'

This PR addresses issue #14

**Comment by nicholebarry** [comment]
Did you want this to be internal only? At the moment, this can only be accessed internally --- I can't pass bin_arr_3d into ps_wrapper.

**Comment by bhazelton** [comment]
oops, that's a mistake. I'll fix it, thanks!

**Comment by bhazelton** [comment]
@nicholebarry where are we on this PR? has it been tested? I'd like to merge it so things don't diverge...

**Comment by nicholebarry** [comment]
It's on the backburner while I frantically try to graduate

**Comment by bhazelton** [comment]
gotcha. I'll leave you out of it.

**Comment by bhazelton** [comment]
This has now been verified.

**Pull request merged**
