### PR TITLE
functionalize uvf cube read in, other minor fixes

### PR DESCRIPTION
**Pull request by bhazelton**

### CODE REVIEW

**Comment by bhazelton** [comment]
@rlbyrne I just pushed a fix to your log binning problem to this branch. Can you check that it works for you?

@mwilensky768 this branch is also supposed to fix your problem, if it works for you can you approve it?

**Comment by rlbyrne** [comment]
On testing, the path to the uvf cubes defaults to `/FHD_output/`, rather than the FHD output location given in the call.

**Comment by bhazelton** [comment]
@rlbyrne @mwilensky768 I'd like to merge this in, I think it fixes a number of different issues as well as adding some nice functionality. So when either of you have time, can you run some sort of test on it and make sure it works for you? If there's a situation that you're aware of where things break, I'd especially like you to run that with this branch and let me know if it's fixed.

**Review by mwilensky768 — APPROVED** [review]
I haven't done comprehensive testing of each and every feature in this PR, however I have been running on this branch a number of standard eppsilon runs and can verify that some of the bugs are definitely fixed. The new functionality that I think I have made use of are:

(1) The comp_1d functionality.
(2) The `get_cube_uvf_input` function (I think)
(3) Line 444 of `ps_image_to_uvf` (getting rid of the pix_window multiply, happens in a couple other places too) 
(4) The `uvf_slice_plot` vertical axis fix.

**Pull request merged**
